### ISSUE TITLE
Error when using MMoItems plugin

### ISSUE THREAD

**Issue by pjindras** [erikzimmermann/TradeSystem#480] opened 2023-08-09 08:15 UTC
**Describe the bug**
Error while using mmoitems item, maybe incompatibility.
https://pastebin.com/wJ4k9ibQ

**Screenshots**
https://pastebin.com/wJ4k9ibQ

**Discord contact**: detektiv_tank

**Comment by erikzimmermann** [comment] 2023-08-09 08:28
Duplicate of #477

**Comment by erikzimmermann** [comment] 2023-08-09 08:29
You can download the most recent file here: https://github.com/erikzimmermann/TradeSystem/actions/runs/5805600258

**Closed by erikzimmermann** 2023-08-09 08:28 UTC
Labels: bug
