### ISSUE TITLE
Trading System need updating to 1.20.4

### ISSUE THREAD

**Issue by AccioAce** [erikzimmermann/TradeSystem#505] opened 2024-01-21 05:52 UTC
**Describe the bug**
Trading system need updating to 1.20.4 as the trades are very much bugged on 1.20.4 version. 

**Discord contact**: accioace

**Comment by kylemarham** [comment] 2024-01-21 13:00
+1

**Comment by erikzimmermann** [comment] 2024-02-23 10:57
Duplicate of #507

**Closed by erikzimmermann** 2024-02-23 10:57 UTC
Labels: bug
