### ISSUE TITLE
Taxes ang log

### ISSUE THREAD

**Issue by daniel-skopek** [erikzimmermann/TradeSystem#482] opened 2023-08-25 13:43 UTC
I would appreciate it if taxes were added. The tax percentages could be set in the config, and when trading between players it would cost a few % less to send money (or cost the player sending the money more).

The second suggestion is the possibility to extend the log time. It seems to me that now only the logs from the last time are displayed. If this is the case, it would be great if it would be possible to set longer log retention.

**Comment by erikzimmermann** [comment] 2023-08-25 14:23
Duplicate of #281

Please upvote the other issue. I'm planning to work on new stuff so this will be implemented in a few weeks.

The logging stuff should be persistent with SQLite or MySQL. Please check your config for that. I'm also working on a Grafana template which is coming soon via TradeAudit 👋🏻

**Closed** 2023-08-30 13:19 UTC
Labels: feature
