### ISSUE TITLE
Error in TradeSystem plugin

### ISSUE THREAD

**Issue by TheEndIsBack** [erikzimmermann/TradeSystem#510] opened 2024-02-29 07:17 UTC
It keeps giving this error, even though it is already in the console, and it also gives an error when I enter /ts log, I would like it to be resolved, because I love the plugin

[18:42:34 WARN]: Exception in thread "Craft Scheduler Thread - 8" org.apache.commons.lang.UnhandledException: Plugin TradeSystem v2.5.2 generated an exception while executing task 1362
[18:42:34 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:57)
[18:42:34 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22)
[18:42:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[18:42:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[18:42:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[18:42:34 WARN]: Caused by: java.lang.NoClassDefFoundError: org/sqlite/SQLiteException
[18:42:34 WARN]:        at de.codingair.tradesystem.spigot.database.DatabaseHandler.getMigrationHandler(DatabaseHandler.java:110)
[18:42:34 WARN]:        at de.codingair.tradesystem.spigot.database.DatabaseHandler.access$100(DatabaseHandler.java:17)
[18:42:34 WARN]:        at de.codingair.tradesystem.spigot.database.DatabaseHandler$1.run(DatabaseHandler.java:31)
[18:42:34 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59)
[18:42:34 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53)
[18:42:34 WARN]:        ... 4 more
[18:42:34 WARN]: Caused by: java.lang.ClassNotFoundException: org.sqlite.SQLiteException
[18:42:34 WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[18:42:34 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[18:42:34 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[18:42:34 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
[18:42:34 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
[18:42:34 WARN]:        ... 9 more

**Comment by erikzimmermann** [comment] 2024-04-12 08:55
Duplicate of #518

**Closed by erikzimmermann** 2024-04-12 08:55 UTC
Labels: bug
